// Mocks generated by Mockito 5.4.6 from annotations
// in voice_todo/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:flutter/material.dart' as _i10;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:voice_todo/models/todo_item.dart' as _i4;
import 'package:voice_todo/models/vocabulary_entry.dart' as _i13;
import 'package:voice_todo/providers/todo_provider.dart' as _i3;
import 'package:voice_todo/providers/voice_provider.dart' as _i7;
import 'package:voice_todo/services/custom_vocabulary_service.dart' as _i12;
import 'package:voice_todo/services/notification_service.dart' as _i14;
import 'package:voice_todo/services/sqlite_service.dart' as _i11;
import 'package:voice_todo/services/voice_recognition_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TodoProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoProvider extends _i1.Mock implements _i3.TodoProvider {
  MockTodoProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.TodoItem> get todos => (super.noSuchMethod(
        Invocation.getter(#todos),
        returnValue: <_i4.TodoItem>[],
      ) as List<_i4.TodoItem>);

  @override
  List<_i4.TodoItem> get incompleteTodos => (super.noSuchMethod(
        Invocation.getter(#incompleteTodos),
        returnValue: <_i4.TodoItem>[],
      ) as List<_i4.TodoItem>);

  @override
  List<_i4.TodoItem> get completedTodos => (super.noSuchMethod(
        Invocation.getter(#completedTodos),
        returnValue: <_i4.TodoItem>[],
      ) as List<_i4.TodoItem>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  int get totalCount => (super.noSuchMethod(
        Invocation.getter(#totalCount),
        returnValue: 0,
      ) as int);

  @override
  int get incompleteCount => (super.noSuchMethod(
        Invocation.getter(#incompleteCount),
        returnValue: 0,
      ) as int);

  @override
  int get completedCount => (super.noSuchMethod(
        Invocation.getter(#completedCount),
        returnValue: 0,
      ) as int);

  @override
  double get completionRate => (super.noSuchMethod(
        Invocation.getter(#completionRate),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadTodos() => (super.noSuchMethod(
        Invocation.method(
          #loadTodos,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addTodo(_i4.TodoItem? todo) => (super.noSuchMethod(
        Invocation.method(
          #addTodo,
          [todo],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addTodos(List<_i4.TodoItem>? todos) => (super.noSuchMethod(
        Invocation.method(
          #addTodos,
          [todos],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setReminder({
    required String? todoId,
    required int? count,
    required Duration? interval,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReminder,
          [],
          {
            #todoId: todoId,
            #count: count,
            #interval: interval,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelReminder(String? todoId) => (super.noSuchMethod(
        Invocation.method(
          #cancelReminder,
          [todoId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTodo(_i4.TodoItem? todo) => (super.noSuchMethod(
        Invocation.method(
          #updateTodo,
          [todo],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTodoWithValidation(_i4.TodoItem? todo) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTodoWithValidation,
          [todo],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTodo(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodo,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTodos(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodos,
          [ids],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markAsCompleted(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsCompleted,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markAsUncompleted(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsUncompleted,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> completeAllTodos() => (super.noSuchMethod(
        Invocation.method(
          #completeAllTodos,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> filterByCategory(String? category) => (super.noSuchMethod(
        Invocation.method(
          #filterByCategory,
          [category],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> filterByPriority(String? priority) => (super.noSuchMethod(
        Invocation.method(
          #filterByPriority,
          [priority],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> searchTodos(String? keyword) => (super.noSuchMethod(
        Invocation.method(
          #searchTodos,
          [keyword],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetFilter() => (super.noSuchMethod(
        Invocation.method(
          #resetFilter,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [VoiceProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceProvider extends _i1.Mock implements _i7.VoiceProvider {
  MockVoiceProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.VoiceStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i8.VoiceStatus.uninitialized,
      ) as _i8.VoiceStatus);

  @override
  String get recognizedText => (super.noSuchMethod(
        Invocation.getter(#recognizedText),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#recognizedText),
        ),
      ) as String);

  @override
  String get correctedText => (super.noSuchMethod(
        Invocation.getter(#correctedText),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#correctedText),
        ),
      ) as String);

  @override
  bool get isListening => (super.noSuchMethod(
        Invocation.getter(#isListening),
        returnValue: false,
      ) as bool);

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setContext(_i10.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #setContext,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<bool> requestPermissionsWithDialog() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissionsWithDialog,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> startListening() => (super.noSuchMethod(
        Invocation.method(
          #startListening,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i4.TodoItem>> stopListening() => (super.noSuchMethod(
        Invocation.method(
          #stopListening,
          [],
        ),
        returnValue: _i5.Future<List<_i4.TodoItem>>.value(<_i4.TodoItem>[]),
      ) as _i5.Future<List<_i4.TodoItem>>);

  @override
  _i5.Future<void> cancelListening() => (super.noSuchMethod(
        Invocation.method(
          #cancelListening,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> parseAndAddTodos() => (super.noSuchMethod(
        Invocation.method(
          #parseAndAddTodos,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SqliteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSqliteService extends _i1.Mock implements _i11.SqliteService {
  MockSqliteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<String> insertTodo(_i4.TodoItem? todo) => (super.noSuchMethod(
        Invocation.method(
          #insertTodo,
          [todo],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #insertTodo,
            [todo],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> insertTodos(List<_i4.TodoItem>? todos) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTodos,
          [todos],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTodo(_i4.TodoItem? todo) => (super.noSuchMethod(
        Invocation.method(
          #updateTodo,
          [todo],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTodo(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodo,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTodos(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodos,
          [ids],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i4.TodoItem?> getTodoById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTodoById,
          [id],
        ),
        returnValue: _i5.Future<_i4.TodoItem?>.value(),
      ) as _i5.Future<_i4.TodoItem?>);

  @override
  _i5.Future<List<_i4.TodoItem>> getAllTodos() => (super.noSuchMethod(
        Invocation.method(
          #getAllTodos,
          [],
        ),
        returnValue: _i5.Future<List<_i4.TodoItem>>.value(<_i4.TodoItem>[]),
      ) as _i5.Future<List<_i4.TodoItem>>);

  @override
  _i5.Future<List<_i4.TodoItem>> getIncompleteTodos() => (super.noSuchMethod(
        Invocation.method(
          #getIncompleteTodos,
          [],
        ),
        returnValue: _i5.Future<List<_i4.TodoItem>>.value(<_i4.TodoItem>[]),
      ) as _i5.Future<List<_i4.TodoItem>>);

  @override
  _i5.Future<List<_i4.TodoItem>> getCompletedTodos() => (super.noSuchMethod(
        Invocation.method(
          #getCompletedTodos,
          [],
        ),
        returnValue: _i5.Future<List<_i4.TodoItem>>.value(<_i4.TodoItem>[]),
      ) as _i5.Future<List<_i4.TodoItem>>);

  @override
  _i5.Future<List<_i4.TodoItem>> getTodosByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodosByCategory,
          [category],
        ),
        returnValue: _i5.Future<List<_i4.TodoItem>>.value(<_i4.TodoItem>[]),
      ) as _i5.Future<List<_i4.TodoItem>>);

  @override
  _i5.Future<List<_i4.TodoItem>> getTodosByPriority(String? priority) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodosByPriority,
          [priority],
        ),
        returnValue: _i5.Future<List<_i4.TodoItem>>.value(<_i4.TodoItem>[]),
      ) as _i5.Future<List<_i4.TodoItem>>);

  @override
  _i5.Future<List<_i4.TodoItem>> getTodosByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodosByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i5.Future<List<_i4.TodoItem>>.value(<_i4.TodoItem>[]),
      ) as _i5.Future<List<_i4.TodoItem>>);

  @override
  _i5.Future<List<_i4.TodoItem>> searchTodos(String? keyword) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTodos,
          [keyword],
        ),
        returnValue: _i5.Future<List<_i4.TodoItem>>.value(<_i4.TodoItem>[]),
      ) as _i5.Future<List<_i4.TodoItem>>);

  @override
  _i5.Future<Map<String, dynamic>> getTodoStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getTodoStatistics,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> clearAllTodos() => (super.noSuchMethod(
        Invocation.method(
          #clearAllTodos,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [CustomVocabularyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomVocabularyService extends _i1.Mock
    implements _i12.CustomVocabularyService {
  MockCustomVocabularyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  int get vocabularySize => (super.noSuchMethod(
        Invocation.getter(#vocabularySize),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addEntry(
    String? incorrect,
    String? correct,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [
            incorrect,
            correct,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> removeEntry(String? incorrect) => (super.noSuchMethod(
        Invocation.method(
          #removeEntry,
          [incorrect],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  Map<String, String> getAllEntries() => (super.noSuchMethod(
        Invocation.method(
          #getAllEntries,
          [],
        ),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  List<_i13.VocabularyEntry> getAllEntriesDetailed() => (super.noSuchMethod(
        Invocation.method(
          #getAllEntriesDetailed,
          [],
        ),
        returnValue: <_i13.VocabularyEntry>[],
      ) as List<_i13.VocabularyEntry>);

  @override
  _i13.VocabularyEntry? getEntry(String? incorrect) =>
      (super.noSuchMethod(Invocation.method(
        #getEntry,
        [incorrect],
      )) as _i13.VocabularyEntry?);

  @override
  _i5.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reinitialize() => (super.noSuchMethod(
        Invocation.method(
          #reinitialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i14.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> scheduleReminder({
    required int? id,
    required String? title,
    required String? body,
    required DateTime? scheduledDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleReminder,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #scheduledDate: scheduledDate,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<DateTime>> scheduleMultipleReminders({
    required int? todoId,
    required String? title,
    required DateTime? deadline,
    required int? count,
    required Duration? interval,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleMultipleReminders,
          [],
          {
            #todoId: todoId,
            #title: title,
            #deadline: deadline,
            #count: count,
            #interval: interval,
          },
        ),
        returnValue: _i5.Future<List<DateTime>>.value(<DateTime>[]),
      ) as _i5.Future<List<DateTime>>);

  @override
  _i5.Future<void> cancelReminder(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelReminder,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAllRemindersForTodo(
    int? todoId, {
    int? count = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelAllRemindersForTodo,
          [todoId],
          {#count: count},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAllReminders() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllReminders,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i15.PendingNotificationRequest>> getPendingNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingNotifications,
          [],
        ),
        returnValue: _i5.Future<List<_i15.PendingNotificationRequest>>.value(
            <_i15.PendingNotificationRequest>[]),
      ) as _i5.Future<List<_i15.PendingNotificationRequest>>);
}
